name: template
description: An application that provide a code repository template for flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Android : Version Name               + Version Code
# iOS     : CFBundleShortVersionString + CFBundleVersion
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter


  # Provide iOS Cupertino style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Provide a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.0

  # Provide a script to update all of the app platform logo
  flutter_launcher_icons: ^0.10.0

  # Provide a script to update all of the app platform splash screen
  flutter_native_splash: ^2.2.11

# Terminal Run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: asset/image/app-logo.png
  remove_alpha_ios: true

# Terminal Run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: asset/image/app-splash.png
  color: '#FFFFFF'

# The following section is specific to Flutter packages.
flutter:

  # Provide Android Material style icons.
  uses-material-design: true

  # Declare Multimedia Resources
  assets:
    - asset/image/
